### ISSUE TITLE
Injecting but no menu or anything.

### ISSUE THREAD

**Issue by Navoichyk** [rrpvm/LumenSense-beta--deprecated-#1]
I compiled your dll without any errors, but when i try to inject it, nothing shows up. Is the menu button insert? or what is it?

**Comment by rrpvm** [comment]
> I compiled your dll without any errors, but when i try to inject it, nothing shows up. Is the menu button insert? or what is it?

man, now is 2022, not 2020/2021, the pattern of d3d9 device is outdated. Look at ida pro and client_shared3d9.dll

**Comment by Navoichyk** [comment]
> 

Where is that?

**Comment by Navoichyk** [comment]
> > I compiled your dll without any errors, but when i try to inject it, nothing shows up. Is the menu button insert? or what is it?
> 
> man, now is 2022, not 2020/2021, the pattern of d3d9 device is outdated. Look at ida pro and client_shared3d9.dll

You should update this.

**Comment by rrpvm** [comment]
Do It Yourself
